//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMark
    {
        public int bookMarkId { get; set; }
        public int comicId { get; set; }
        public int userId { get; set; }
    
        public virtual Comic Comic { get; set; }
        public virtual UserStory UserStory { get; set; }
    }
}
