//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public int credentialId { get; set; }
        public int groupId { get; set; }
        public int rolesId { get; set; }
    
        public virtual GroupStory GroupStory { get; set; }
        public virtual Role Role { get; set; }
    }
}
